folio-org/folio-perf-test

- Folio-Test-Plans/classification-types/classification-typesTestPlan.jmx
> Fix JMeter script syntax

- Folio-Test-Plans/contributor-types/contributor-typesTestPlan.jmx
- Folio-Test-Plans/instance-format/instance-formatTestPlan.jmx
- Folio-Test-Plans/instance-type/instance-typeTestPlan.jmx
Update JMeter scripts(contributor-types, instance-format, instance-type) to sync-up with the recent release of API implementation changes
> Fix jenkins build

- Folio-Test-Plans/mod-circulation-storage/loan-policy-storage/loan-policy-storageTestPlan.jmx
- Folio-Test-Plans/mod-circulation-storage/loan-rules-storage/loan-rules-storageTestPlan.jmx
1) Fix loan-policy to add UUID in POST/PUT explicitly
2) Fix loan-rules to update with correct policy details
> Fix loan storage and loan-policy

- Folio-Test-Plans/mod-circulation/mod-circulationTestPlan.jmx
https://issues.folio.org/browse/FOLIO-1345
> Add renew-by-id and clean-up previous code

- Folio-Test-Plans/mod-inventory-storage/location-units/location-unitsTestPlan.jmx
Update test plan to extract the first occurrence instead of random occurrence
> location-units: update test plan

- Folio-Test-Plans/mod-circulation/renewals/mod-circulationRenewalsTestPlan.jmx
Fix circulation test plan by adding servicepoint
> fix circulation test

- Folio-Test-Plans/mod-circulation/requests/mod-circulationRequestsTestPlan.jmx
Add service point as part of creating a loan request in mod-circulation
> Fix for mod-circulation requests

- Folio-Test-Plans/mod-circulation/requests/mod-circulationRequestsTestPlan.jmx
updated to include missing request done in UI circulation workflow
> added query for loans by user id

- Folio-Test-Plans/platform-workflow-performance/Platform-workflow-performance.jmx
also increased timeouts to accommodate longer requests
> added debugging to help figure out why certain requests are failing.

- Jenkinsfile.folioci
- Jenkinsfile.platform
- Jenkinsfile.public
- eis/Jenkinsfile.eis.dev
- eis/Jenkinsfile.eis.dev.cleanup
- eis/Jenkinsfile.eis.dev.setup
- eis/Jenkinsfile.eis.int
- eis/Jenkinsfile.eis.int.cleanup
- eis/Jenkinsfile.eis.int.setup
The stable site lags behind and we cannot see the performance improvement that have been committed for a while. Per Jakub, let's change to use snapshot site so we can see improvements sooner.
> Per Jakub, use snapshot not stable to build system.

- Folio-Test-Plans/platform-workflow-performance/Platform-workflow-performance.jmx
These are the sub set that tested as very slow via UI.
> added a half dozen requests that are made from the UI-users app

- Folio-Test-Plans/mod-orders/data-loader/requests/order_line_e_resource_rq.json
- Folio-Test-Plans/mod-orders/data-loader/requests/order_line_p_e_mix_rq.json
- Folio-Test-Plans/mod-orders/data-loader/requests/order_line_physical_rq.json
Performance script for data-loader should be updated because of po_line changes introduced in scope of [MODORDERS-252](https://issues.folio.org/browse/MODORDERS-252) (productIdType changed to UUID format).
Verified on localhost:
> MODORDSTOR-85 - DB Optimization

- eis/Jenkinsfile.eis.int.setup
- shared.groovy
Also enable both backend and frontend modules, so UI can connect to.
> FOLIO-2296: load default reference data for a few core modules

- Folio-Test-Plans/platform-workflow-performance/Platform-workflow-performance.jmx
new test to enable effective location performance measurement
> Folio 2238

- Folio-Test-Plans/mod-kb-ebsco-java/resources/resourcesTestPlan.jmx
Add userDefinedFields for PUT /resources/{id} request
> MODKBEKBJ-335: Add userDefinedFields for PUT request

- Folio-Test-Plans/mod-kb-ebsco-java/titles/titlesTestPlan.jmx
Add userDefinedFields for POST request
> MODKBEKBJ-334: Add userDefinedFields for POST request

- Jenkinsfile.folioci
- Jenkinsfile.integration
- Jenkinsfile.platform
- eis/Jenkinsfile.eis.dev
- eis/Jenkinsfile.eis.dev.cleanup
- eis/Jenkinsfile.eis.dev.setup
- eis/Jenkinsfile.eis.int
- eis/Jenkinsfile.eis.int.cleanup
- eis/Jenkinsfile.eis.int.setup
- eis/Jenkinsfile.eis.int.test
Note not yet folio-snapshot-stable
> FOLIO-2704 Use new FQDN dev.folio.org for folio-snapshot etc

- Jenkinsfile.integration
Added TestRail URL, creds. Added maven line args.
> Folio-2712 TestRail integration

- Jenkinsfile.integration
- shared.groovy
Fixed okapi permissions call and mod-data-export-registration
> Fixed okapi and mod-data-export-registration

- Jenkinsfile.api
- Jenkinsfile.integration
- shared.groovy
Jenkins job for running all Postman api tests  from the [folio-org/folio-api-tests](https://github.com/folio-org/folio-api-tests.git)
Jira task [FOLIO-1380](https://issues.folio.org/browse/FOLIO-1380)
Jenkins job [folio-api-test](https://jenkins-aws.indexdata.com/job/FOLIO_Reference_Builds/job/folio-api-test/)
> FOLIO-1380 set up Postman API test Jenkins job

- Jenkinsfile.integration
- shared.groovy
Enable Cucumber reporting for Jenkins "folio-integration" pipelines
Jira task [FOLIO-2747](https://issues.folio.org/browse/FOLIO-2747)
Jenkins job [FOLIO-2747](https://jenkins-aws.indexdata.com/job/FOLIO_Reference_Builds/job/FOLIO-2747/)
> Folio 2747

- Jenkinsfile.integration
- shared.groovy
> Folio-2747: Fix okapiDns

- config/mod-kb-ebsco.sh
- shared.groovy
pull request FOLIO-3373 in base FOLIO-2982
> Folio 3373

- Jenkinsfile.integration
- shared.groovy
**Adjustment to karate tests should be made**:
- Adjust timeout ( not sufficient now);
- Adjust java ( 8 to 11);
- Add db connection details to mod-notes;
- Increase modules ec2 instance type
**Possible ways to revert changes**
Revert commit, no issues expected, as env is recreated every day.
> Rancher 146

- Folio-Test-Plans/bulk-edit/items/accession-numbers/config.csv
- Folio-Test-Plans/bulk-edit/items/barcodes/config.csv
- Folio-Test-Plans/bulk-edit/items/former-ids/config.csv
- Folio-Test-Plans/bulk-edit/items/holding-uuids/config.csv
- Folio-Test-Plans/bulk-edit/items/hrids/config.csv
- Folio-Test-Plans/bulk-edit/items/uuids/config.csv
[MODBULKED-22](https://issues.folio.org/browse/MODBULKED-22) - Establish performance baseline for item locations bulk updates
> MODBULKED-22 - Establish performance baseline for item locations bulk updates

- Folio-Test-Plans/bulk-edit/items/accession-numbers/Bulk-edit-ItemAccessionNumber-Test-Plan.jmx
- Folio-Test-Plans/bulk-edit/items/barcodes/Bulk-edit-ItemBarcode-Test-Plan.jmx
- Folio-Test-Plans/bulk-edit/items/former-ids/Bulk-edit-ItemFormerId-Test-Plan.jmx
- Folio-Test-Plans/bulk-edit/items/holding-uuids/Bulk-edit-ItemHoldingUUID-Test-Plan.jmx
- Folio-Test-Plans/bulk-edit/items/hrids/Bulk-edit-ItemHRID-Test-Plan.jmx
- Folio-Test-Plans/bulk-edit/items/uuids/Bulk-edit-ItemUUID-Test-Plan.jmx
[MODBULKED-23](https://issues.folio.org/browse/MODBULKED-23) - Establish performance baseline for item status bulk updates
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> MODBULKED-23 - Establish performance baseline for item status bulk updates
